# Generated by Django 5.1.1 on 2024-09-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='autor_do_livro',
            field=models.CharField(default='Autor Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='descricao_do_livro',
            field=models.TextField(default='Descrição não disponível'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='nome_do_livro',
            field=models.CharField(default='Título Desconhecido', max_length=255),
        ),
    ]
