# Generated by Django 5.1.1 on 2024-09-16 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_favoritebook_autor_do_livro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('user', 'book_id')},
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='autor_do_livro',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='descricao_do_livro',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='nome_do_livro',
        ),
    ]
